// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfyk06B1ipyylaL6Mg8OmnU2MG8X9DI8o',
    appId: '1:715655181180:web:29bdcc9f0c4863d39a6af9',
    messagingSenderId: '715655181180',
    projectId: 'social-media-app-d4bb0',
    authDomain: 'social-media-app-d4bb0.firebaseapp.com',
    storageBucket: 'social-media-app-d4bb0.firebasestorage.app',
    measurementId: 'G-LNL7XZKHHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFG5w3on7QzUetER_qqYSVYLzHEh0xlc8',
    appId: '1:715655181180:android:dac5226145b1c5789a6af9',
    messagingSenderId: '715655181180',
    projectId: 'social-media-app-d4bb0',
    storageBucket: 'social-media-app-d4bb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPKjeOEw6raKmW9q8jQGCeSBnhJXz1JAQ',
    appId: '1:715655181180:ios:14bc4969bc9f169f9a6af9',
    messagingSenderId: '715655181180',
    projectId: 'social-media-app-d4bb0',
    storageBucket: 'social-media-app-d4bb0.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPKjeOEw6raKmW9q8jQGCeSBnhJXz1JAQ',
    appId: '1:715655181180:ios:14bc4969bc9f169f9a6af9',
    messagingSenderId: '715655181180',
    projectId: 'social-media-app-d4bb0',
    storageBucket: 'social-media-app-d4bb0.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfyk06B1ipyylaL6Mg8OmnU2MG8X9DI8o',
    appId: '1:715655181180:web:2d0609a1a4b0d28e9a6af9',
    messagingSenderId: '715655181180',
    projectId: 'social-media-app-d4bb0',
    authDomain: 'social-media-app-d4bb0.firebaseapp.com',
    storageBucket: 'social-media-app-d4bb0.firebasestorage.app',
    measurementId: 'G-GJ21PT3NDJ',
  );
}
